spring:
  datasource:
    url: jdbc:mysql://localhost:3306/royalnavghan
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin

  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
  
  